controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  base_controller:
    type: robot_pai/ControllerBase
  ppo_controller:
    type: robot_pai/PPOController